name: Continuous Integration
on: [push]

jobs:
  build-cs:
    name: Build and test C#
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Build and Test Code
        run: |
          dotnet build
          dotnet test
  build-ts:
    name: Build and test Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install & build
        working-directory: ./DotnetTemplate.Web
        run: |
          npm ci
          npm run build
          npm t
          npm run lint