name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Build Code
        run: dotnet build
        
      - name: Install & build
        working-directory: ./DotnetTemplate.Web
        run: |
          npm ci
          npm run build
          npm t
          npm run lint

      - name: C# Tests
        run: dotnet test